modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"
issueTrackerURL="https://github.com/kawaiicakes/mc-musketmod/issues"

[[mods]]
modId="musketmod"
version="${mod_version}"
displayName="Musket Mod"
#updateJSONURL=""
displayURL="https://github.com/kawaiicakes/mc-musketmod"
logoFile="logo.png"
credits="lilypuree, MikhailTapio, Xannosz, SkpC9 for their contribution"
authors="ewewukek, TheAsianAimbot / kawaiicakes"
description='''
Small mod that adds craftable muskets and pistols.
'''
